#!/bin/bash
# This script formats and mounts a USB flash drive.

echo Preparing persistent storage...

if grep -qs '/media/storage' /proc/mounts; then
    echo "Storage drive is mounted."
else
    echo "Storage drive NOT mounted."
fi

echo "User is $USER with id $UID"
id
losetup /dev/loop0 ~/vps-storage
umount /dev/loop0
mkfs.ext4 -F /dev/loop0
mkdir /media/storage
mount -t ext4 /dev/loop0 /media/storage

if grep -qs '/media/storage' /proc/mounts; then
    echo "Storage drive is mounted."
    sudo rm -rf /media/storage/*
    mkdir /media/storage/lost+found
else
    echo "Storage drive NOT mounted."
fi

echo ...finished preparing persistent storage.
