#!/bin/bash
# This script formats and mounts a USB flash drive.

echo Preparing persistent storage...
sudo losetup /dev/loop0 ~/vps-storage
sudo umount /dev/loop0
sudo mkfs.ext4 -F /dev/loop0
sudo mkdir /media/storage
sudo mount -t ext4 /dev/loop0 /media/storage
sudo chown -R $USER:$USER /media/storage/
echo ...finished preparing persistent storage.
