#!/bin/bash

#Copyright 2017 RPiOVN.org
#Licensing Information: http://rpiovn.org/license


#This script should be edited to execute any merge scripts needed to
#merge plugins and theme files before starting ConnextCMS/KeystoneJS.

echo Running finalsetup script

#Run any merge scripts to install plugins or site templates.
#public/merge-site-plugin-files

#cd ~/myCMS

#Copy the /public directory for nginx
#cp -r public/* ~/public

#["/usr/sbin/sshd", "-D", "-p", "4100"]
/usr/sbin/sshd -D -p 3100 &

# Read the username and password and store to variables.
while IFS='' read -r line || [[ -n "$line" ]]; do
    echo "Text read from file: $line"
done < sudopassword

#Change permissions so use can write to persistant storage.
#sudopasswd=$(head -n 1 sudopassword)
#RUN echo $sudopasswd | sudo -S pwd
#RUN sudo chown -R $USER /media/storage


#Launch KeystoneJS and ConnextCMS
exec "$@"
