#!/bin/bash

#Copyright 2017 RPiOVN.org
#Licensing Information: http://rpiovn.org/license


#This script should be edited to execute any merge scripts needed to
#merge plugins and theme files before starting ConnextCMS/KeystoneJS.

echo Running finalsetup script

#Run any merge scripts to install plugins or site templates.
#public/merge-site-plugin-files

#cd ~/myCMS

#Copy the /public directory for nginx
#cp -r public/* ~/public

#["/usr/sbin/sshd", "-D", "-p", "4100"]
/usr/sbin/sshd -D -p 3100 &

# Read the username and password and store to variables.
#INDEX=0
#ARRAY[0]="passwd"
#while IFS='' read -r line || [[ -n "$line" ]]; do
#  ARRAY[INDEX]=$line
  #echo "Text read from file: ${ARRAY[INDEX]}"
#  INDEX=$(($INDEX+1))
#done < sudopassword

#Change permissions so use can write to persistant storage.
username=$(head -n 1 username)
#echo ${ARRAY[0]} | sudo -S pwd
sudo chown -R $username /media/storage


#Launch KeystoneJS and ConnextCMS
exec "$@"
