#!/bin/bash

#Copy the SSH config file to stop the irritating key prompt
#cp config ~/.ssh/

#Run the docker image
docker run -d --rm --name renter-shell -p 6100:6100 -p 3100:3100 -v /home/trout/.p2pvps/logs/connect-client/:/usr/src/app/logs renter-shell
